from __future__ import annotations


TIMELINE_SEED_ITEMS: list[dict[str, str | None]] = [
    {
        "id": "c1-1",
        "job_id": "1",
        "category": "due-date",
        "subtype": None,
        "sender": None,
        "date": "2026-02-01",
        "short_description": "Invoice payment due",
        "details": "Invoice #001 for emergency burst pipe repair. Total: GBP 1,420.00. Payment terms: 14 days.",
    },
    {
        "id": "c1-2",
        "job_id": "1",
        "category": "collexis-handover",
        "subtype": None,
        "sender": "collexis",
        "date": "2026-02-15",
        "short_description": "Case handed to Collexis",
        "details": "Client failed to pay within terms. Case escalated to Collexis for debt recovery.",
    },
    {
        "id": "c1-3",
        "job_id": "1",
        "category": "chase",
        "subtype": "email",
        "sender": "collexis",
        "date": "2026-02-16",
        "short_description": "First chase email sent",
        "details": "Subject: Outstanding Invoice #001 - Payment Reminder\n\nDear Mrs Whitmore,\n\nI hope this email finds you well. I'm writing to remind you that invoice #001 for GBP 1,420.00 remains unpaid. The payment was due on 1st February 2026.\n\nPlease arrange payment at your earliest convenience.\n\nKind regards",
    },
    {
        "id": "c1-4",
        "job_id": "1",
        "category": "chase",
        "subtype": "email",
        "sender": "collexis",
        "date": "2026-03-02",
        "short_description": "Second chase email sent",
        "details": "Subject: Urgent - Outstanding Invoice #001\n\nDear Mrs Whitmore,\n\nFurther to my previous email, invoice #001 for GBP 1,420.00 remains unpaid and is now significantly overdue.\n\nPlease treat this as a matter of urgency.\n\nKind regards",
    },
    {
        "id": "c1-5",
        "job_id": "1",
        "category": "chase",
        "subtype": "voicemail",
        "sender": "collexis",
        "date": "2026-03-10",
        "short_description": "Voicemail left, no answer",
        "details": "Called 07712 334 891 at 09:45. No answer. Left voicemail requesting callback regarding outstanding payment.",
    },
    {
        "id": "c2-1",
        "job_id": "2",
        "category": "due-date",
        "subtype": None,
        "sender": None,
        "date": "2026-02-10",
        "short_description": "Invoice payment due",
        "details": "Invoice #002 for consumer unit upgrade. Total: GBP 2,800.00.",
    },
    {
        "id": "c2-2",
        "job_id": "2",
        "category": "chase",
        "subtype": "email",
        "sender": "you",
        "date": "2026-02-20",
        "short_description": "Chase email to accounts",
        "details": "Sent to accounts@holtcommercial.co.uk requesting payment of GBP 2,800.",
    },
    {
        "id": "c2-3",
        "job_id": "2",
        "category": "conversation",
        "subtype": "phone",
        "sender": "you",
        "date": "2026-02-25",
        "short_description": "Phone call with M. Holt",
        "details": "Spoke with M. Holt directly. He claims GBP 2,400 was verbally agreed. Informed him the signed quote confirms GBP 2,800. He said he would look into it and call back. No callback received.",
    },
    {
        "id": "c2-4",
        "job_id": "2",
        "category": "letter",
        "subtype": None,
        "sender": "you",
        "date": "2026-03-10",
        "short_description": "Letter of Action posted",
        "details": "Formal Letter Before Action sent via Royal Mail signed-for delivery to 9 Cavendish Place, Leeds LS1 2HG. 14-day deadline to respond or settle.",
    },
    {
        "id": "c3-1",
        "job_id": "3",
        "category": "due-date",
        "subtype": None,
        "sender": None,
        "date": "2026-03-01",
        "short_description": "Remaining balance due",
        "details": "Balance of GBP 2,600 due (total GBP 3,100 less GBP 500 deposit paid at booking).",
    },
    {
        "id": "c3-2",
        "job_id": "3",
        "category": "chase",
        "subtype": "email",
        "sender": "you",
        "date": "2026-03-15",
        "short_description": "Friendly payment reminder sent",
        "details": "Polite email reminder sent to r.patel@gmail.com noting the outstanding balance of GBP 2,600.",
    },
]
